import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

/**
 * The rules this codebase already follows, made enforceable.
 *
 * @remarks
 * There were ten `eslint-disable-next-line react-hooks/exhaustive-deps`
 * comments in `src/` before this file existed. Each one documents a deliberate
 * decision — `useAutosave` keys its debounce on character *identity*, the flush
 * bus registers once with a stable ref — and every one of them enforced
 * nothing, because no linter ever ran. A suppression with no rule behind it is
 * a comment that looks like a guarantee.
 *
 * The selection is deliberately the rules the tree already passes rather than
 * an aspirational set: a linter wired into CI has to be green on the day it
 * lands or it teaches everyone to ignore it. Notably **not** enabled are
 * `eslint-plugin-react-hooks` v7's React Compiler rules (`purity`,
 * `immutability`, `set-state-in-effect`, `refs`, …), which its `recommended`
 * preset now turns on. They are worth adopting, but they are a refactor, not a
 * configuration change — see the roadmap.
 */
export default tseslint.config(
  {
    // `docs/` is generated by TypeDoc and gitignored; `dist/` is the build.
    ignores: ['dist/**', 'docs/**', 'dev-dist/**', 'coverage/**', 'output/**', 'tests/**'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // The two rules the existing suppressions are written against.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // Fast Refresh only preserves state for a module that exports components
      // alone. Several context modules export a provider next to its hook by
      // design, so this is a warning rather than an error.
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // A leading underscore is this codebase's existing convention for a
      // parameter that exists to satisfy a signature.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],

      // On. This was deferred when the config landed — 129 mechanical rewrites
      // of error handling in the same change that introduces a linter is how a
      // linter gets reverted — and taken afterwards, as its own commit, once
      // the config was green.
      //
      // It matters more here than the rule's name suggests. Every one of those
      // sites was in `src/storage/repositories/`, and every one interpolated the
      // caught error into a string: `` `${e}` `` renders a Dexie failure as
      // "ConstraintError: Key already exists" and throws away both the stack and
      // `err.name`. In an app whose only copy of the user's data is one
      // IndexedDB database, that is the difference between a bug report saying
      // "saving failed" and one that distinguishes a `QuotaExceededError` — the
      // device is out of room, act now — from a validation failure. `cause` is
      // additive: the message the user sees is unchanged.
      'preserve-caught-error': 'error',
    },
  },
  {
    // The tests reach for `any` to build deliberately malformed input — a
    // system definition missing a required field, a bundle row of the wrong
    // shape — which is the point of those tests. The invariant this codebase
    // actually holds is zero `any` in *shipped* source, so that is where the
    // rule is enforced.
    files: ['**/*.test.{ts,tsx}'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
  {
    // Node globals, not browser: config and tooling files run outside the app.
    files: ['*.config.{ts,js}', 'scripts/**/*.{ts,js}'],
    languageOptions: { globals: globals.node },
  },
);
