import type { TimelineItem, TimelineMarker, TimelineTrack } from './types';

export const timelineMockTracks: TimelineTrack[] = [
  {
    id: 'track-session',
    label: 'Session',
    kind: 'session',
    order: 0,
    visible: true,
    collapsible: false,
    colorToken: '--color-gold',
  },
  {
    id: 'track-encounters',
    label: 'Encounters',
    kind: 'encounter',
    order: 1,
    visible: true,
    collapsible: true,
    colorToken: '--color-danger',
  },
  {
    id: 'track-npcs',
    label: 'NPC Arcs',
    kind: 'npc',
    order: 2,
    visible: true,
    collapsible: true,
    colorToken: '--color-accent',
  },
  {
    id: 'track-quests',
    label: 'Quest Beats',
    kind: 'quest',
    order: 3,
    visible: true,
    collapsible: true,
    colorToken: '--color-warning',
  },
  {
    id: 'track-travel',
    label: 'Travel',
    kind: 'travel',
    order: 4,
    visible: true,
    collapsible: true,
    colorToken: '--color-info',
  },
];

export const timelineMockItems: TimelineItem[] = [
  {
    id: 'session-12',
    trackId: 'track-session',
    title: 'Session 12',
    subtitle: 'Whispers Under the Bridge',
    start: '2026-04-01T18:00:00',
    end: '2026-04-01T22:30:00',
    type: 'range',
    kind: 'session',
    variant: 'accent',
    noteId: 'note-session-12',
  },
  {
    id: 'enc-bridge-ambush',
    trackId: 'track-encounters',
    title: 'Bridge Ambush',
    start: '2026-04-01T18:45:00',
    end: '2026-04-01T19:30:00',
    type: 'range',
    kind: 'combat',
    variant: 'danger',
    status: 'ended',
    noteId: 'note-enc-bridge-ambush',
    tags: ['combat', 'bandits'],
  },
  {
    id: 'enc-fog-shrine',
    trackId: 'track-encounters',
    title: 'Fog Shrine Negotiation',
    start: '2026-04-01T20:05:00',
    end: '2026-04-01T20:55:00',
    type: 'range',
    kind: 'social',
    variant: 'default',
    status: 'ended',
    noteId: 'note-fog-shrine',
    tags: ['social', 'shrine'],
  },
  {
    id: 'npc-mayor',
    trackId: 'track-npcs',
    title: 'Mayor Introduced',
    start: '2026-04-01T19:10:00',
    type: 'milestone',
    kind: 'npc',
    variant: 'default',
    noteId: 'note-mayor-intro',
    tags: ['npc'],
  },
  {
    id: 'npc-rival',
    trackId: 'track-npcs',
    title: 'Rival Leaves the Shrine',
    start: '2026-04-01T20:42:00',
    type: 'point',
    kind: 'npc',
    variant: 'muted',
    noteId: 'note-rival',
    tags: ['npc', 'rival'],
  },
  {
    id: 'quest-lantern',
    trackId: 'track-quests',
    title: 'Recover the Sunken Lantern',
    start: '2026-04-01T18:15:00',
    end: '2026-04-01T22:10:00',
    type: 'range',
    kind: 'quest',
    variant: 'warning',
    status: 'active',
    noteId: 'note-lantern',
    tags: ['quest'],
  },
  {
    id: 'travel-marsh',
    trackId: 'track-travel',
    title: 'Marsh Road',
    start: '2026-04-01T18:00:00',
    end: '2026-04-01T18:40:00',
    type: 'range',
    kind: 'travel',
    variant: 'success',
    noteId: 'note-marsh-road',
    tags: ['travel'],
  },
];

export const timelineMockMarkers: TimelineMarker[] = [
  {
    id: 'marker-sunset',
    label: 'Sunset',
    at: '2026-04-01T19:45:00',
    kind: 'world-event',
    colorToken: '--color-gold',
  },
  {
    id: 'marker-break',
    label: 'Break',
    at: '2026-04-01T20:00:00',
    kind: 'session-break',
    colorToken: '--color-border',
  },
];
